id: IEC9DA148
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:44:01+00:00'
last_modified: '2022-06-08T16:52:20.614739+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9289
  title: བླང་དོར་གསལ་བར་སྟོན་པའི་དྲང་ཐིག་དྭངས་ཤེལ་མེ་ལོང་ཉེར་གཅིག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    ABE1:
      image_group_id: I1KG9376
      title: ''
      total_pages: 84
      order: 1
      base_file: ABE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
