id: P010696
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:21.657716
source_metadata:
  id: bdr:W1KG9289
  title: བླང་དོར་གསལ་བར་སྟོན་པའི་དྲང་ཐིག་དྭངས་ཤེལ་མེ་ལོང་ཉེར་གཅིག་པ།
  author: ''
  volumes:
    b18eaac63d4d4495bcf0bc5e942df225:
      image_group_id: I1KG9376
      title: ''
      volume_number: 1
      total_pages: 84
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
